### PR TITLE
Remove notice and add info

### PR DESCRIPTION
**Pull request by HarelM**
## 📑 Description

This github action creates a notice in the github summary screen, I don't think this is intended.
Instead, I moved this to the console logging.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

The following is the screen shot:
image

### CODE REVIEW

**Comment by bbonkr** [comment]
@HarelM 

Thank you for your interest.

I had wanted to verify this in the workflow log.

Close this PR as `wontfix`.

Have a nice weekend.

**Comment by HarelM** [comment]
Thanks for the quick response!
Is there a way to remove this notice somehow from my github actions?
I want it to be empty in case there are no problems in the build etc.
What do you suggest I should do in order to remove this?

**Comment by bbonkr** [comment]
@HarelM 

I'll add option in the input which shows log or not.

**Comment by HarelM** [comment]
Great! Thanks!!

**Pull request closed without merging**
